### ISSUE TITLE
Can not set min color temperature in Scenes

### ISSUE THREAD

**Issue by HelloThisIsFlo** [edvaldeysteinsson/IKEA-Tradfri#1]
Hey,

First thanks for your amazing work.

I have a problem. When creating a scene, I can not set the color temperature to the minimum (2200K).
See picture.

Any clue? 
If you lead me in the right direction, I'll try to fix that in a pull request ;)

Thanks.
Florian
![screenshot_20171209-135615](https://user-images.githubusercontent.com/10831649/33796284-28228526-dce9-11e7-9e91-c5c5d2bdf569.jpg)

**Comment by edvaldeysteinsson** [comment]
This is a limitation in the SmartThings scenes, [https://community.smartthings.com/t/scenes-beta/103474/185](https://community.smartthings.com/t/scenes-beta/103474/185)
