### ISSUE TITLE
New colour bulbs not recognised

### ISSUE THREAD

**Issue by thecivvie** [edvaldeysteinsson/IKEA-Tradfri#3]
The new Ikea Tradfri colour bulbs are not recognized. Is there anything I can give you that would help

**Comment by edvaldeysteinsson** [comment]
Those are not supported by this handler, this one is only for the colour temperature bulbs.
You could give this one a try, [SmartThings-IKEA-Tradfri-RGB](https://github.com/puzzle-star/SmartThings-IKEA-Tradfri-RGB)
