### ISSUE TITLE
Tradfri E27 1000lm

### ISSUE THREAD

**Issue by alex117uk** [edvaldeysteinsson/IKEA-Tradfri#5]
Hello,

I have just bought some E27 1000lm which do not appear to be in the device handler list. I already have paried 6 GU10 bulbs with no issue. Is this something that can be added to the script? I have tried adding myself but am new to all this and it appears to have no affect. When attempting to par (same method I used with the GU10 which was quick and easy) my smartthings hub cannot see the bulbs.

Any help would be much appreciated.

**Comment by edvaldeysteinsson** [comment]
That's not a color temperature bulb. It's only dimmable so just include it and go to the [Smartthings IDE](https://graph.api.smartthings.com/) and edit the type and select ZigBee Dimmer or ZLL Dimmer bulb

**Comment by alex117uk** [comment]
Hi there, my issue was that the smartthings hub simply cannot see the bulbs at all. I know how to connect, distance very close but it does not see them at all. I understand once connected it will be an 'unknown device type' but I can't get to that stage

**Comment by edvaldeysteinsson** [comment]
That would not be related to any DTH, sounds like a  general inclusion issues. Check the SmartThings forum, you're more likely to get it working by posting there. https://community.smartthings.com
